spring:
  profiles:
    active: default
  
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: Admin
    password: Admin
    virtual-host: saket
  application:
    name: company-service
RabbitMq:
 queue:
  command: commandQueue
  order: orderQueue     
server:
  port: 8102    

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8200}/eureka/
    fetch-registry: true
    register-with-eureka: true  
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
ribbon:
  eureka:
   enabled: true    
   
---
spring:
  profiles: default
  
  datasource:
    url: jdbc:postgresql://localhost:5432/company_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver